import React, { useState } from "react";
//import add icon
import addSvg from "../../assets/img/add.svg";
//import library for working with request
import axios from "axios";

const AddTaskForm = ({ list, onAddTask }) => {
  //useState hook switches visibility of form
  const [visibleForm, setVisibleForm] = useState(false);
  //useState hook for changing text value in input form
  const [inputValue, setInputValue] = useState("");
  //useState hook for setting loading state of page
  const [isLoading, setIsLoading] = useState(false);

  // function that switches visibility state of form
  const toggleFormVisible = () => {
    setVisibleForm(!visibleForm);
    //clears input value
    setInputValue("");
  };

  //function that will add created Task to list of Tasks
  const addTask = () => {
    //generating created task
    const obj = {
      //id is generated by back-end
      listId: list.id,
      text: inputValue,
      completed: false,
    };
    //sets Loading state of page before creating task
    setIsLoading(true);

    //creates new task on back-end
    axios
      .post(" http://localhost:3001/tasks", obj)
      .then(({ data }) => {
        //callback function that creates task
        onAddTask(list.id, data);
        //callback function that will hide add task form after creating task
        toggleFormVisible();
      })
      .catch(() => {
        alert("Error while adding new task");
      })
      .finally(() => {
        //after creating task in list of Tasks set loaded state of page
        setIsLoading(false);
      });
  };

  return (
    <div className="tasks__form">
      {!visibleForm ? (
        // Add New task blocks - appears if visible Form state is false
        <div onClick={toggleFormVisible} className="tasks__form-new">
          <img src={addSvg} alt="Add icon" />
          <span>New Task</span>
        </div>
      ) : (
        // Create Task Form block - appears if visible Form State is true
        <div className="visible__form">
          <input
            value={inputValue}
            className="field"
            type="text"
            placeholder="Task text"
            onChange={(e) => setInputValue(e.target.value)}
          />
          <div className="tasks__form-block">
            {/* button that adds task */}
            <button disabled={isLoading} onClick={addTask} className="button">
              {isLoading ? "Adding..." : "Add Task"}
            </button>
            {/* button that hides form */}
            <button onClick={toggleFormVisible} className="button button--grey">
              Cancel
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default AddTaskForm;
